### ISSUE TITLE
`flock --update` fails

### ISSUE THREAD

**Issue by Antonasg** [jakeheis/Flock#11]
When running `flock --update` I get the following error:
```
precondition failed: Failure normalizing https://github.com/jakeheis/Flock, absolute paths should start with '/': file /Users/buildnode/jenkins/workspace/oss-swift-3.1-package-osx/swiftpm/Sources/Basic/Path.swift, line 495
```

**Comment by jakeheis** [comment]
Try upgrading FlockCLI (`brew upgrade jakeheis/repo/flock`)  and then doing a hard reset of the Flock directory `flock --reset && flock --build`

**Comment by jakeheis** [comment]
Closing for now, feel free to reopen if the issue has not been resolved
