### ISSUE TITLE
Error: no such module 'SSH'

### ISSUE THREAD

**Issue by seboslaw** [jakeheis/Flock#14]
When running "flock deploy" I'm getting an "error: no such module 'SSH'" while Swift is trying to compile the module "Flock" (see screenshot).
I have the libssh2 installed via 'brew install libssh2'.

![svogelsang_mac15-2____development_projects_portfolioscanner_portfolioscanner-server_ _-zsh_ _196x47](https://user-images.githubusercontent.com/97770/29613045-6f830bb4-8804-11e7-9eda-08683fe09555.png)

**Comment by jakeheis** [comment]
Can you run `brew upgrade flock`  and also make sure you're using the latest version of Flock and see if this error persists?

**Comment by seboslaw** [comment]
Hey @jakeheis . Strange...homebrew is telling me:

Warning: jakeheis/repo/flock 0.2.1 is already installed

though I can see that 0.3.2 is the latest version. Already ran brew update to get the latest packages but no luck :(

**Comment by im-ng** [comment]
One more here. Get stuck with this same issue.

**Comment by jakeheis** [comment]
This should be fixed now; please reopen if need be!
