### ISSUE TITLE
Unable to install Flock

### ISSUE THREAD

**Issue by pascalfriedrich** [jakeheis/Flock#16]
Getting following output when trying to install Flock manually. Installing via Homebew also failed.

`Fetching https://github.com/jakeheis/SwiftCLI
Fetching https://github.com/kylef/PathKit
Fetching https://github.com/onevcat/Rainbow
Fetching https://github.com/jakeheis/Spawn
Fetching https://github.com/kylef/Spectre
Cloning https://github.com/kylef/Spectre
Resolving https://github.com/kylef/Spectre at 0.7.2
Cloning https://github.com/onevcat/Rainbow
Resolving https://github.com/onevcat/Rainbow at 2.0.1
Cloning https://github.com/jakeheis/SwiftCLI
Resolving https://github.com/jakeheis/SwiftCLI at 3.1.0
Cloning https://github.com/jakeheis/Spawn
Resolving https://github.com/jakeheis/Spawn at 0.0.6
Cloning https://github.com/kylef/PathKit
Resolving https://github.com/kylef/PathKit at 0.7.1
Compile Swift Module 'Spawn' (1 sources)
Compile Swift Module 'Rainbow' (11 sources)
Compile Swift Module 'Spectre' (8 sources)
Compile Swift Module 'SwiftCLI' (25 sources)
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/Rainbow-4833422609927903952/Sources/ModesExtractor.swift:37:69: warning: 'characters' is deprecated: Please use String or Substring directly
        var index = string.index(string.startIndex, offsetBy: token.characters.count)
                                                                    ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/Rainbow-4833422609927903952/Sources/ModesExtractor.swift:39:22: warning: 'characters' is deprecated: Please use String or Substring directly
        while string.characters[index] != "m" {
                     ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/Rainbow-4833422609927903952/Sources/ModesExtractor.swift:40:39: warning: 'characters' is deprecated: Please use String or Substring directly
            codesString.append(string.characters[index])
                                      ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/Rainbow-4833422609927903952/Sources/ModesExtractor.swift:44:33: warning: 'characters' is deprecated: Please use String or Substring directly
        let codes = codesString.characters.split(separator: ";", maxSplits: Int.max, omittingEmptySubsequences: false).flatMap { UInt8(String($0)) }
                                ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/Rainbow-4833422609927903952/Sources/ModesExtractor.swift:46:78: warning: 'characters' is deprecated: Please use String or Substring directly
        let endIndex = string.index(string.endIndex, offsetBy: -"\(token)0m".characters.count)
                                                                             ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/Rainbow-4833422609927903952/Sources/ModesExtractor.swift:47:34: warning: 'characters' is deprecated: Please use String or Substring directly
        let text = String(string.characters[startIndex ..< endIndex])
                                 ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/Rainbow-4833422609927903952/Sources/ModesExtractor.swift:61:35: warning: 'characters' is deprecated: Please use String or Substring directly
        var outer = String(string.characters[index]) //Start index should be the ESC control code
                                  ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/Rainbow-4833422609927903952/Sources/ModesExtractor.swift:64:57: warning: 'characters' is deprecated: Please use String or Substring directly
            index = string.index(index, offsetBy: token.characters.count)
                                                        ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/Rainbow-4833422609927903952/Sources/ModesExtractor.swift:66:26: warning: 'characters' is deprecated: Please use String or Substring directly
            while string.characters[index] != ";" {
                         ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/Rainbow-4833422609927903952/Sources/ModesExtractor.swift:67:43: warning: 'characters' is deprecated: Please use String or Substring directly
                codesString.append(string.characters[index])
                                          ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/Rainbow-4833422609927903952/Sources/ModesExtractor.swift:73:35: warning: 'characters' is deprecated: Please use String or Substring directly
            outer = String(string.characters[index])
                                  ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/Rainbow-4833422609927903952/Sources/ModesExtractor.swift:77:77: warning: 'characters' is deprecated: Please use String or Substring directly
        let endIndex = string.index(string.endIndex, offsetBy: -"\(token);".characters.count)
                                                                            ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/Rainbow-4833422609927903952/Sources/ModesExtractor.swift:78:34: warning: 'characters' is deprecated: Please use String or Substring directly
        let text = String(string.characters[startIndex ..< endIndex])
                                 ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/Spectre--9185491864710013835/Sources/Expectation.swift:98:22: warning: redundant conformance constraint 'Key': 'Equatable'
public func == <Key: Equatable, Value: Equatable> (lhs: Expectation<[Key: Value]>, rhs: [Key: Value]) throws {
                     ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/Spectre--9185491864710013835/Sources/Expectation.swift:98:57: note: conformance constraint 'Key': 'Equatable' inferred from type here
public func == <Key: Equatable, Value: Equatable> (lhs: Expectation<[Key: Value]>, rhs: [Key: Value]) throws {
                                                        ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/Spectre--9185491864710013835/Sources/Expectation.swift:108:22: warning: redundant conformance constraint 'Key': 'Equatable'
public func != <Key: Equatable, Value: Equatable> (lhs: Expectation<[Key: Value]>, rhs: [Key: Value]) throws {
                     ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/Spectre--9185491864710013835/Sources/Expectation.swift:108:57: note: conformance constraint 'Key': 'Equatable' inferred from type here
public func != <Key: Equatable, Value: Equatable> (lhs: Expectation<[Key: Value]>, rhs: [Key: Value]) throws {
                                                        ^
Compile Swift Module 'PathKit' (1 sources)
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/SwiftCLI-8466703425035036135/Sources/SwiftCLI/ArgumentListManipulator.swift:54:28: warning: 'characters' is deprecated: Please use String or Substring directly
                node.value.characters.dropFirst().forEach {
                           ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/SwiftCLI-8466703425035036135/Sources/SwiftCLI/CompletionGenerator.swift:105:63: warning: 'characters' is deprecated: Please use String or Substring directly
                let sortedNames = option.names.sorted(by: {$0.characters.count > $1.characters.count})
                                                              ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/SwiftCLI-8466703425035036135/Sources/SwiftCLI/CompletionGenerator.swift:105:85: warning: 'characters' is deprecated: Please use String or Substring directly
                let sortedNames = option.names.sorted(by: {$0.characters.count > $1.characters.count})
                                                                                    ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/SwiftCLI-8466703425035036135/Sources/SwiftCLI/CompletionGenerator.swift:105:63: warning: 'characters' is deprecated: Please use String or Substring directly
                let sortedNames = option.names.sorted(by: {$0.characters.count > $1.characters.count})
                                                              ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/SwiftCLI-8466703425035036135/Sources/SwiftCLI/CompletionGenerator.swift:105:85: warning: 'characters' is deprecated: Please use String or Substring directly
                let sortedNames = option.names.sorted(by: {$0.characters.count > $1.characters.count})
                                                                                    ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/SwiftCLI-8466703425035036135/Sources/SwiftCLI/HelpMessageGenerator.swift:36:30: warning: 'characters' is deprecated: Please use String or Substring directly
            if routable.name.characters.count > length {
                             ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/SwiftCLI-8466703425035036135/Sources/SwiftCLI/HelpMessageGenerator.swift:37:37: warning: 'characters' is deprecated: Please use String or Substring directly
               return routable.name.characters.count
                                    ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/SwiftCLI-8466703425035036135/Sources/SwiftCLI/HelpMessageGenerator.swift:36:30: warning: 'characters' is deprecated: Please use String or Substring directly
            if routable.name.characters.count > length {
                             ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/SwiftCLI-8466703425035036135/Sources/SwiftCLI/HelpMessageGenerator.swift:37:37: warning: 'characters' is deprecated: Please use String or Substring directly
               return routable.name.characters.count
                                    ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/SwiftCLI-8466703425035036135/Sources/SwiftCLI/HelpMessageGenerator.swift:78:38: warning: 'characters' is deprecated: Please use String or Substring directly
                if option.identifier.characters.count > length {
                                     ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/SwiftCLI-8466703425035036135/Sources/SwiftCLI/HelpMessageGenerator.swift:79:46: warning: 'characters' is deprecated: Please use String or Substring directly
                    return option.identifier.characters.count
                                             ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/SwiftCLI-8466703425035036135/Sources/SwiftCLI/HelpMessageGenerator.swift:78:38: warning: 'characters' is deprecated: Please use String or Substring directly
                if option.identifier.characters.count > length {
                                     ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/SwiftCLI-8466703425035036135/Sources/SwiftCLI/HelpMessageGenerator.swift:79:46: warning: 'characters' is deprecated: Please use String or Substring directly
                    return option.identifier.characters.count
                                             ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/SwiftCLI-8466703425035036135/Sources/SwiftCLI/HelpMessageGenerator.swift:43:91: warning: 'characters' is deprecated: Please use String or Substring directly
            let spacing = String(repeating: " ", count: maxNameLength + 4 - routable.name.characters.count)
                                                                                          ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/SwiftCLI-8466703425035036135/Sources/SwiftCLI/Option.swift:18:74: warning: 'characters' is deprecated: Please use String or Substring directly
        let spacing = String(repeating: " ", count: padding - identifier.characters.count)
                                                                         ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/.build/checkouts/PathKit--9185519632264250829/Sources/PathKit.swift:43:34: warning: 'characters' is deprecated: Please use String or Substring directly
      path = p.substring(from: p.characters.index(after: p.startIndex))
                                 ^
Compile Swift Module 'FlockCLI' (12 sources)
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/main.swift:8:5: warning: 'setup(name:version:description:)' is deprecated: Create a new CLI object: let cli = CLI(..)
CLI.setup(name: "flock", version: "0.0.1")
    ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/main.swift:10:5: warning: 'router' is deprecated: Create a new CLI object: let cli = CLI(..)
CLI.router = FlockRouter()
    ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/FlockRouter.swift:11:7: error: type 'FlockRouter' does not conform to protocol 'Router'
class FlockRouter: Router {
      ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/FlockRouter.swift:13:10: note: candidate has non-matching type '([Command], ArgumentList) -> Command?'
    func route(commands: [Command], arguments: ArgumentList) -> Command? {
         ^
SwiftCLI.Router:2:17: note: protocol requires function 'route(routables:arguments:)' with type '([Routable], ArgumentList) -> RouteResult'; do you want to add a stub?
    public func route(routables: [Routable], arguments: SwiftCLI.ArgumentList) -> SwiftCLI.RouteResult
                ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/main.swift:11:5: error: 'versionCommand' is unavailable: Create the CLI object with a nil version and register a custom version command
CLI.versionCommand = VersionCommand()
    ^~~~~~~~~~~~~~
SwiftCLI.CLI:11:23: note: 'versionCommand' has been explicitly marked unavailable here
    public static var versionCommand: <null>
                      ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/main.swift:12:19: error: 'HelpCommand' cannot be constructed because it has no accessible initializers
CLI.helpCommand = HelpCommand()
                  ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/main.swift:14:5: warning: 'register(command:)' is deprecated: Create a new CLI object: let cli = CLI(..)
CLI.register(command: InitCommand())
    ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/main.swift:15:5: warning: 'register(command:)' is deprecated: Create a new CLI object: let cli = CLI(..)
CLI.register(command: BuildCommand())
    ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/main.swift:16:5: warning: 'register(command:)' is deprecated: Create a new CLI object: let cli = CLI(..)
CLI.register(command: UpdateCommand())
    ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/main.swift:17:5: warning: 'register(command:)' is deprecated: Create a new CLI object: let cli = CLI(..)
CLI.register(command: CleanCommand())
    ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/main.swift:18:5: warning: 'register(command:)' is deprecated: Create a new CLI object: let cli = CLI(..)
CLI.register(command: ResetCommand())
    ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/main.swift:19:5: warning: 'register(command:)' is deprecated: Create a new CLI object: let cli = CLI(..)
CLI.register(command: CreateTaskCommand())
    ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/main.swift:20:5: warning: 'register(command:)' is deprecated: Create a new CLI object: let cli = CLI(..)
CLI.register(command: NukeCommand())
    ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/main.swift:26:10: warning: 'go()' is deprecated: Create a new CLI object: let cli = CLI(..)
exit(CLI.go())
         ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/CreateTaskCommand.swift:25:86: warning: 'characters' is deprecated: Please use String or Substring directly
            name = name.substring(to: name.index(name.endIndex, offsetBy: taskSuffix.characters.count))
                                                                                     ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/CreateTaskCommand.swift:29:34: warning: 'characters' is deprecated: Please use String or Substring directly
        if let colonIndex = name.characters.index(of: ":") {
                                 ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/CreateTaskCommand.swift:41:19: warning: 'CLIError' is deprecated: use CLI.Error instead
            throw CLIError.error("\(path) already exists".red)
                  ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/FlockCommand.swift:38:19: warning: 'CLIError' is deprecated: use CLI.Error instead
            throw CLIError.error("Error: ".red + "Flock has not been initialized in this directory yet - run `flock --init`")
                  ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/ForwardCommand.swift:31:19: warning: 'CLIError' is deprecated: use CLI.Error instead
            throw CLIError.error("Error: Flock must be successfully built before tasks can be run".red)
                  ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/HelpCommand.swift:15:9: error: overriding non-open let outside of its defining module
    let name = "--help"
        ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/HelpCommand.swift:15:9: error: cannot override with a stored property 'name'
    let name = "--help"
        ^
SwiftCLI.HelpCommand:2:16: note: attempt to override property here
    public let name: String
               ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/HelpCommand.swift:16:9: error: overriding non-open let outside of its defining module
    let shortDescription = "Prints help information"
        ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/HelpCommand.swift:16:9: error: cannot override with a stored property 'shortDescription'
    let shortDescription = "Prints help information"
        ^
SwiftCLI.HelpCommand:3:16: note: attempt to override property here
    public let shortDescription: String
               ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/HelpCommand.swift:21:10: error: overriding non-open instance method outside of its defining module
    func execute() throws {
         ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/HelpCommand.swift:21:10: error: overriding declaration requires an 'override' keyword
    func execute() throws {
         ^
    override 
SwiftCLI.HelpCommand:4:17: note: overridden declaration is here
    public func execute() throws
                ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/HelpCommand.swift:13:7: error: cannot inherit from non-open class 'HelpCommand' outside of its defining module
class HelpCommand: SwiftCLI.HelpCommand, FlockCommand {
      ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/HelpCommand.swift:28:17: error: value of type 'Command' has no member 'signature'
            if !command.signature.isEmpty {
                ^~~~~~~ ~~~~~~~~~
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/HelpCommand.swift:29:29: error: value of type 'Command' has no member 'signature'
                name += " \(command.signature)"
                            ^~~~~~~ ~~~~~~~~~
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/HelpCommand.swift:50:63: warning: 'characters' is deprecated: Please use String or Substring directly
        let spacing = String(repeating: " ", count: 20 - name.characters.count)
                                                              ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/InitCommand.swift:22:19: warning: 'CLIError' is deprecated: use CLI.Error instead
            throw CLIError.error("Error: ".red + "Flock has already been initialized")
                  ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/InitCommand.swift:41:23: warning: 'CLIError' is deprecated: use CLI.Error instead
                throw CLIError.error("\(path) must not already exist".red)
                      ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/InitCommand.swift:93:23: warning: 'CLIError' is deprecated: use CLI.Error instead
                throw CLIError.error("Couldn't open .gitignore stream")
                      ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/InitCommand.swift:96:63: warning: 'characters' is deprecated: Please use String or Substring directly
            gitIgnore.write(appendText, maxLength: appendText.characters.count)
                                                              ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/Paths.swift:41:31: warning: 'characters' is deprecated: Please use String or Substring directly
    for _ in 0..<(12 - action.characters.count) {
                              ^
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/VersionCommand.swift:17:26: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
        print("Version: \(CLI.version)")
                         ^~~~~~~~~~~~~
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/VersionCommand.swift:17:31: note: use 'String(describing:)' to silence this warning
        print("Version: \(CLI.version)")
                         ~~~~~^~~~~~~~
                          String(describing:  )
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/VersionCommand.swift:17:31: note: provide a default value to avoid this warning
        print("Version: \(CLI.version)")
                         ~~~~~^~~~~~~~
                                      ?? <#default value#>
/Users/pascalfriedrich/FlockCLI/FlockCLI/Sources/VersionCommand.swift:17:31: warning: 'version' is deprecated: Create a new CLI object: let cli = CLI(..)
        print("Version: \(CLI.version)")
                              ^
error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/pascalfriedrich/FlockCLI/FlockCLI/.build/release.yaml main`

**Comment by jakeheis** [comment]
Homebrew installation is no longer support; please install using Mint!
