### ISSUE TITLE
supervisorctl fails to load vapor

### ISSUE THREAD

**Issue by anthonycastelli** [jakeheis/Flock#6]
When running `flock deploy` everything appears to be going well up until the point of `supervisorctl` reloading. 

When it comes to loading up vapor, it fails. The vapor.conf is there, but even running it manually through SSH it fails. I've never used supervisor so i'm at a loss here. Any ideas on what could be going wrong? 

```
Task vapor:write-conf begun:
On deploy@9.9.9.9: mkdir -p /home/deploy/logs
On deploy@9.9.9.9: echo "[program:vapor]
command=/home/deploy/www/App/current/.build/release/App
process_name=%(process_num)s
autostart=false
autorestart=unexpected
stdout_logfile=/home/deploy/logs/vapor.log
stderr_logfile=/home/deploy/logs/vapor.err
" > /etc/supervisor/conf.d/vapor.conf
On deploy@9.9.9.9: supervisorctl reread
vapor: available
On deploy@9.9.9.9: supervisorctl update
vapor: added process group
On deploy@9.9.9.9: supervisorctl restart vapor:*
vapor:0: ERROR (no such file)
```

**Comment by jakeheis** [comment]
Have you already built your project in release mode (i.e. does the executable `/home/deploy/www/App/current/.build/release/App` exist)? I'm guessing supervisor is erroring out because it doesn't, but thats a relatively blind guess

**Comment by anthonycastelli** [comment]
Isn't flock deploy supposed to do that?

**Comment by jakeheis** [comment]
It should be, I'm just trying to narrow down if the issue lies in the build part of `flock deploy` or the Vapor part. If you manually run `/home/deploy/www/App/current/.build/release/App`, does your server start?

**Comment by anthonycastelli** [comment]
I had a " " in my executable name. Im now getting `ERROR (spawn error)` and I think it's because it just can't find config files. 🤔

**Comment by anthonycastelli** [comment]
After digging and looking into this, it appears the production environment is not being set on the app when its launching which is causing issues

**Comment by anthonycastelli** [comment]
After spending hours figuring out what has gone wrong, I realized that everything is fixed with appending `--env=production` to the `command=\(Paths.executable)` line for the supervisor conf. I've been trying to comprehend how Flock handles environments, but it seems like that it doesn't and all you are doing is calling the `Production()` Configuration. I'm not sure how to dynamically handle this with your implementation, but when launching the vapor process, the `--env=...` should be attached to the command.

**Comment by jakeheis** [comment]
Is attaching `--env=...` to the invocation of the command a Vapor-specific trait?

**Comment by jakeheis** [comment]
After looking into this a little it appears it is Vapor-specific. As such I'll be closing this issue and implementing `--env` for `VaporFlock`

**Comment by anthonycastelli** [comment]
Yeah it is. You also have to pass environment variables to the environment option in supervisor to get them passed into the app.
