### ISSUE TITLE
Password protected ssh key asks for password on each command

### ISSUE THREAD

**Issue by mdab121** [jakeheis/Flock#8]
Just like in the title – password prompt shows up before each flock command.
The key is added to the session via `ssh-add` earlier, but it gets ignored by Flock's shell sessions.

I'm using ZSH by default, but invoking Flock from bash doesn't seem to change anything.

**Comment by jakeheis** [comment]
The switch to using NMSSH instead of ssh calls will fix this issue; transition is WIP, a93f3142cc69e57d41f198cc7b6486120d2d437d

**Comment by jakeheis** [comment]
Fixed now with usage of https://github.com/jakeheis/Shout
